### ISSUE TITLE
일반 공지사항 등록>화면 확인

### ISSUE THREAD

**Issue by Awesomeit-NSM** [awesomeitdev/awesomeit_eaction#5]
'등록한 공지사항이 날짜 기준 내림차순으로 정렬되어 표기

현재 API에서 오름차순 정렬로 줌.
( http://slb-5984586.ncloudslb.com/api/smhl/tchr/ntce )

**Comment by Kim-SangTaek** [comment]
이것은 관리자 화면을 보시면 아시겠지만, 화면에 있는 "정렬순번" 이 지금보니 모두 0으로 등록되어 있던데, 값을 입력해서 정렬을 맞춰주십시오.
