### ISSUE TITLE
본 글이 수정되거나, 댓글이 등록 되면 목록에서 해당 글은 최신으로 변경되어야함

### ISSUE THREAD

**Issue by Awesomeit-NSM** [awesomeitdev/awesomeit_eaction#6]
본 글이 수정되거나, 댓글이 등록 되면 목록에서 해당 글은 최신으로 변경 되어야함
현재는 수정 및 댓글 등록에도 최신 화 가 되지 않음

server 수정 사항으로 판단됨

**Comment by Kim-SangTaek** [comment]
@jeongyeol-son 

"최신으로 변경"이 시스템적으로 무엇을 의미하는지는 모르겠습니다만, 현재 저희쪽에서는 글의 변경 사항을 Push 로 능동적으로 보내는 부분과   목록 조회시 리턴하는 Last_qna_no 컬럼을 통해서, 댓글이 변경되었음을 인지할 수 있도록 구현되어 있습니다. 

위 2가지를 가지고 처리를 하시거나, 더 필요하신게 있다면,  "최신으로 변경" 이 API 적으로 어떻게 동작하기를 원하는 것인지 구체적으로 말씀해 주셔야 할듯 싶습니다.

**Comment by Kim-SangTaek** [comment]
@jeongyeol-son  마지막 댓글 혹은 수정일시 기준으로 정렬을 변경하였습니다. 이게 복잡하게 찾아야 하기에, 부하가 걸리는 작업이라서 복잡하게 찾지 않도록 하기 위해 내부적으로 구조가 변경이 되었습니다. 혹시 모르니 테스트 꼼꼼하게 부탁드립니다.
