### ISSUE TITLE
qna push 발생 시 학생의 알림함에 쌓이는 현상 제거

### ISSUE THREAD

**Issue by Awesomeit-NSM** [awesomeitdev/awesomeit_eaction#7]
qna push 발생 시 학생의 알림함에 쌓이는 현상 제거
서버 쪽에서 예외처리 필요할 듯 보임
서버 쪽 요청 필요.

**Comment by Kim-SangTaek** [comment]
@jeongyeol-son 
저희쪽에서는 Push 발생시 아래와 같이 보내고 있습니다.  data_type 을 보고, 알림함(?)에 쌓이지 않도록 처리하시면 될듯 싶습니다.
![image](https://user-images.githubusercontent.com/23306140/215650436-1e8942de-06ee-4eeb-8699-ea157e390b4a.png)

**Comment by jeongyeol-son** [comment]
@Kim-SangTaek 현재 알림함의 경우 PUSH를 받아 자체적으로 처리 하는 것이 아니고 API 통신을 이용하여, 가져오고 있습니다. 해당 API는 http://slb-5984586.ncloudslb.com/api/smhl/pmsg?acct_id=S000000014&acct_type=S  입니다.

**Comment by Kim-SangTaek** [comment]
@jeongyeol-son   해당 API 에서 qna push noti 는 빠지도록 처리되었습니다. 확인 부탁드립니다.
