### ISSUE TITLE
답글 작성시 게시글 작성자가 아닌 답글 작성자에게 알림이 오는 현상

### ISSUE THREAD

**Issue by Awesomeit-NSM** [awesomeitdev/awesomeit_eaction#8]
현재 답글 작성시 게시글 작성자가 아닌 답글 작성자에게 알림이 오는 현상이 있습니다.
확인을 부탁드립니다.

Ex. A학생이 게시글 작성, B선생님이 답글 작성시 A가 아닌 B에게 알림이 옴

**Comment by Kim-SangTaek** [comment]
@Awesomeit-NSM 

저희쪽 소스를 다시 확인해 봤습니다만, 저희쪽에서는 모든 글의 "수신자"에게 Push 가 가고 있습니다. 
즉, 최초 게시글의 경우, 받는자에게,   댓글의 경우 "원글 작성자"에게 가도록 구현 되어 있습니다.
다시 한번 확인을 해보시는게 좋을것 같습니다.

**Comment by KwonGeneral** [comment]
receiver_id가 잘못되어있었습니다. 현재 배포버전은 해당 부분을 수정해서 정상적으로 동작하도록 변경했습니다!
